# dbconfig
db.url=jdbc:mysql://localhost:3306/beidou2?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
db.username=root
db.password=123456
db.driverClassName=com.mysql.cj.jdbc.Driver

# option config
db.maxPoolSize=10
db.minIdle=2
db.idleTimeout=30000